import { Comfortaa } from "next/font/google";
import "./globals.css";
const inter = Comfortaa({ subsets: ["latin"] });
const fondo5 = "https://corsialminuto.it/img/logo-adstrategy-footer-cinza.png";

export const metadata = {
  title: "Corsi Al Minuto",
  description: "Generated by crls-app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/images/icon.png",
        href: "/images/icon-light.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/images/icon.png",
        href: "/images/icon-dark.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <div className="bg-gray-50 p-8 flex flex-col items-center">
          <img src={fondo5} alt="" style={{ width: "200px" }} />
        </div>
        <h1 className="hidden w-full p-5 py-20 bg-gray-900 text-gray-50 text-center text-sm">
          Copyright @ 2024
        </h1>
      </body>
    </html>
  );
}
